[package]
name = "poetry-no-cap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "poetry_no_cap"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
clap = "4.1.6"
pyo3 = "0.18.1"
